name: 'Altruist'
color: '#660000'
enabled: true
announcement: You're an Altruist!
announcement-sound: 'minecraft:block.note_block.bit'
announcement-pitch: 2.0
description:
  - "Sacrifice yourself to revive any player!"
winning-ends-games: true
bells: 0
see-own-team: false
selection:
  minimum: 0
  maximum: 1
  percentage: 16.7