name: 'Doctor'
color: 'light_purple'
enabled: true
announcement: You're a Doctor!
announcement-sound: 'minecraft:block.note_block.bit'
announcement-pitch: 2.0
description:
  - Heal your teammates and assist them!
winning-ends-games: true
bells: 0
see-own-team: false
selection:
  minimum: 0
  percentage: 16.7