name: 'Innocent'
color: 'green'
enabled: true
announcement: You're Innocent!
announcement-sound: 'minecraft:block.note_block.bit'
announcement-pitch: 2.0
description:
  - You're very defenseless. Stay alive until time
  - runs out or eliminate all opposing parties.
winning-ends-games: true
bells: 0
see-own-team: false
selection:
  remainder: true