name: '<green>Innocent'
description:
  - '<gray>Very defenseless. Stay alive until time'
  - '<gray>runs out or eliminate all opposing parties.'
abilities: []
limit: -1
winning-ends-games: true
coins: 0