name: 'Jester'
color: '#ff85f7'
enabled: true
announcement: You're a Jester!
announcement-sound: 'minecraft:block.note_block.bass'
announcement-pitch: 0.5
description:
  - 'Die by the hands of the innocent!'
winning-ends-games: true
bells: 4
see-own-team: true
selection:
  remainder: true