name: 'Traitor'
color: 'red'
enabled: true
announcement: You're a Traitor!
announcement-sound: 'minecraft:block.note_block.bass'
announcement-pitch: 0.5
description:
  - 'Eliminate all opposing players before'
  - 'time runs out to win!'
winning-ends-games: true
bells: 4
see-own-team: true
selection:
  remainder: true