name: '<red>Traitor'
enabled: true
announcement: <red>You're a Traitor!
announcement-sound: 'minecraft:block.note_block.bass'
announcement-pitch: 0.5
description:
  - '<gray>Eliminate all opposing players before'
  - '<gray>time runs out to win!'
limit: -1
winning-ends-games: true
coins: 4
see-own-team: true
selection:
  remainder: true