name: 'Underling'
color: '#ff6333'
enabled: true
announcement: You're an Underling!
announcement-sound: 'minecraft:block.note_block.bass'
announcement-pitch: 0.5
description:
  - '<gray>Find your fellow traitors and'
  - '<gray>assist them on eliminating all opposers.'
winning-ends-games: true
bells: 0
see-own-team: false
selection:
  minimum: 0
  percentage: 50.0