role-chance-dividend: 1.05

# Dagger
backstab-cooldown: 200 # ticks

# Compass
compass-cooldown: 100 # ticks

# Creepanade
grenade-cooldown: 200 # ticks
grenade-radius: 5.0
grenade-damage: 20.0
grenade-minimum-damage: 5.0
grenade-velocity-multiplier: 0.5
grenade-delay: 5 # ticks

# Explosive
explosive-cooldown: 400 # ticks
explosive-radius: 3.5
explosive-damage: 40.0
explosive-minimum-damage: 10.0
explosive-velocity-multiplier: 0.5
explosive-delay: 5 # ticks
