name: Deceit
description: "Murder Mystery style minigames"
version: '${version}'

main: pro.fazeclan.river.deceit.Deceit
api-version: '26.2'
load: POSTWORLD

authors: [ riversflowing ]
website: https://github.com/flowingforever

dependencies:
  server:
    Jarona:
      load: BEFORE
      required: true
    NBTAPI:
      load: BEFORE
      required: true
      join-classpath: true
